// Copyright 2023 Subatomix Research Inc.
// SPDX-License-Identifier: ISC

namespace Mixer;

[TestFixture]
public class BaselineTests
{
    [Test]
    public void Nongeneric()
    {
        var result = RunMixinGenerator(
            "using Mixer; namespace Test; [Mixin]                   class Source { }",
            "using Mixer; namespace Test; [Include(typeof(Source))] class Target { }"
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.0.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
            }

            #nullable restore
            #endregion Source


            """
        });
    }

    [Test]
    public void Generic()
    {
        var result = RunMixinGenerator(
            "using Mixer; namespace Test { [Mixin]           class Source { } }",
            "using Mixer; namespace Test { [Include<Source>] class Target { } }"
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
            }

            #nullable restore
            #endregion Source


            """
        });
    }
}
