// Copyright 2023 Subatomix Research Inc.
// SPDX-License-Identifier: ISC

namespace Mixer.Tests.Functional;

// To cover: MixinGeneralizer.VisitAliasQualifiedName

[TestFixture]
public class AliasQualifiedNameTests
{
    [Test]
    public void Simple()
    {
        new FunctionalTestBuilder()
        .WithSourceAndTargetKinds(Class)
        .WithInput(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            $source Source
            {
                global::System.Text.StringBuilder?
                    PropertyWhoseTypeIsAliasQualifiedName => default;
            }

            [Include<Source>]
            partial $target Target { }
            """
        )
        .ExpectGeneratedSource(
            "Test.Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial $target Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                global::System.Text.StringBuilder?
                    PropertyWhoseTypeIsAliasQualifiedName => default;
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }

    [Test]
    public void MixinType()
    {
        new FunctionalTestBuilder()
        .WithSourceAndTargetKinds(Class)
        .WithInput(
            """
            using Mixer;

            [Mixin]
            $source Source
            {
                global::Source?
                    PropertyWhoseTypeIsMixinType => default;
            }

            [Include<Source>]
            partial $target Target { }
            """
        )
        .ExpectGeneratedSource(
            "Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            #region Source
            #nullable enable

            partial $target Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                global::Target?
                    PropertyWhoseTypeIsMixinType => default;
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }

    [Test]
    public void PredefinedType()
    {
        new FunctionalTestBuilder()
        .WithSourceAndTargetKinds(Class)
        .WithInput(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            $source Source
            {
                global::System.Int32?
                    PropertyWhoseTypeIsPredefined => default;
            }

            [Include<Source>]
            partial $target Target { }
            """
        )
        .ExpectGeneratedSource(
            "Test.Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial $target Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                int?
                    PropertyWhoseTypeIsPredefined => default;
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }
}
