// Copyright 2023 Subatomix Research Inc.
// SPDX-License-Identifier: ISC

namespace Mixer.Tests.Functional;

[TestFixture]
public class AttributeTests
{
    [Test]
    public void Simple()
    {
        new FunctionalTestBuilder()
        .WithInput(
            """
            using System;
            using Mixer;

            namespace Test;

            class FooAttribute : Attribute { }

            [Mixin]
            [Foo]
            $source Source { }

            [Include<Source>]
            partial $target Target { }
            """
        )
        .ExpectGeneratedSource(
            "Test.Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            [global::Test.FooAttribute]
            partial $target Target
            {
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }

    [Test]
    public void SharedAttributeList()
    {
        new FunctionalTestBuilder()
        .WithInput(
            """
            using System;
            using Mixer;

            namespace Test;

            class FooAttribute : Attribute { }

            [Mixin, Foo]
            $source Source { }

            [Include<Source>]
            partial $target Target { }
            """
        )
        .ExpectGeneratedSource(
            "Test.Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            [global::Test.FooAttribute]
            partial $target Target
            {
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }

    [Test]
    public void MultiLineAttribute()
    {
        new FunctionalTestBuilder()
        .WithInput(
            """
            using System;
            using Mixer;

            namespace Test;

            class FooAttribute : Attribute { }

            [Mixin]
            [Foo(
                // stuff
            )]
            $source Source { }

            [Include<Source>]
            partial $target Target { }
            """
        )
        .ExpectGeneratedSource(
            "Test.Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            [global::Test.FooAttribute(
                // stuff
            )]
            partial $target Target
            {
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }
}
