// Copyright 2023 Subatomix Research Inc.
// SPDX-License-Identifier: ISC

namespace Mixer.Tests.Functional;

[TestFixture]
public class BaseListTests
{
    [Test]
    public void Simple()
    {
        new FunctionalTestBuilder().WithInput(
            """
            using Mixer;

            namespace Test;

            class Foo { }
            interface IBar { }

            [Mixin]
            class Source : Foo, IBar { }

            [Include<Source>]
            partial class Target { }
            """
        )
        .ExpectGeneratedSource(
            "Test.Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
                : global::Test.Foo, global::Test.IBar
            {
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }

    [Test]
    public void ClosedGeneric()
    {
        new FunctionalTestBuilder().WithInput(
            """
            using Mixer;

            namespace Test;

            interface IFoo<T0, T1> { }
            class Bar { }

            [Mixin]
            class Source : IFoo<int, Bar> { }

            [Include<Source>]
            partial class Target { }
            """
        )
        .ExpectGeneratedSource(
            "Test.Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
                : global::Test.IFoo<int, global::Test.Bar>
            {
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }

    [Test]
    public void OpenGeneric()
    {
        new FunctionalTestBuilder().WithInput(
            """
            using Mixer;

            namespace Test;

            interface IFoo<T0, T1> { }
            class Bar { }

            [Mixin]
            class Source<T0, T1> : IFoo<T0, T1> { }

            [Include<Source<int, Bar>>]
            partial class Target { }
            """
        )
        .ExpectGeneratedSource(
            // TODO: Should use keyword `int` instead of type name.
            "Test.Target.1.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
                : global::Test.IFoo<global::System.Int32, global::Test.Bar>
            {
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }
}
