// Copyright 2023 Subatomix Research Inc.
// SPDX-License-Identifier: ISC

namespace Mixer;

[TestFixture]
public class FieldTests
{
    [Test]
    public void Simple()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;
            #pragma warning disable CS0649 // Field '...' is never assigned to

            namespace Test;

            class Thing { }

            [Mixin]
            class Source
            {
                public Thing? TheThing;
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                public global::Test.Thing? TheThing;
            }

            #nullable restore
            #endregion

            """
        });
    }

    [Test]
    public void Constant()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            class Source
            {
                public const int TheNumber = 42;
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                public const int TheNumber = 42;
            }

            #nullable restore
            #endregion

            """
        });
    }

    [Test]
    public void Static()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            class Thing { }

            [Mixin]
            class Source
            {
                public static readonly Thing TheThing = new();
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                public static readonly global::Test.Thing TheThing = new();
            }

            #nullable restore
            #endregion

            """
        });
    }
}
