// Copyright 2023 Subatomix Research Inc.
// SPDX-License-Identifier: ISC

namespace Mixer.Tests.Functional;

[TestFixture]
public class InGlobalNamespaceTests
{
    [Test]
    public void Test()
    {
        new FunctionalTestBuilder().WithInput(
            """
            [Mixer.Mixin]
            class Source { }

            [Mixer.Include(typeof(Source))]
            partial class Target { }
            """
        )
        .ExpectGeneratedSource(
            "Target.0.g.cs",
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            #region Source
            #nullable enable

            partial class Target
            {
            }

            #nullable restore
            #endregion
            """
        )
        .Test();
    }
}
