// Copyright 2023 Subatomix Research Inc.
// SPDX-License-Identifier: ISC

namespace Mixer;

[TestFixture]
public class NestedTypeTests
{
    [Test]
    public void Class()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            class Source
            {
                protected class ThingDoer
                {
                    public void DoTheThing() { }
                }
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                protected class ThingDoer
                {
                    public void DoTheThing() { }
                }
            }

            #nullable restore
            #endregion

            """
        });
    }

    [Test]
    public void Struct()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            class Source
            {
                private readonly ref struct ThingDoer
                {
                    public void DoTheThing() { }
                }
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                private readonly ref struct ThingDoer
                {
                    public void DoTheThing() { }
                }
            }

            #nullable restore
            #endregion

            """
        });
    }

    [Test]
    public void Interface()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            class Source
            {
                internal interface IThingDoer
                {
                    void DoTheThing();
                }
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                internal interface IThingDoer
                {
                    void DoTheThing();
                }
            }

            #nullable restore
            #endregion

            """
        });
    }

    [Test]
    public void RecordClass()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            class Source
            {
                protected record class Thing(string? Name)
                //               ^^^^^ optional
                {
                    public bool IsNamed => Name is { Length: > 0 };
                }
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                protected record class Thing(string? Name)
                //               ^^^^^ optional
                {
                    public bool IsNamed => Name is { Length: > 0 };
                }
            }

            #nullable restore
            #endregion

            """
        });
    }

    [Test]
    public void RecordStruct()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            class Source
            {
                private protected readonly record struct Thing(string? Name)
                {
                    public bool IsNamed => Name is { Length: > 0 };
                }
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                private protected readonly record struct Thing(string? Name)
                {
                    public bool IsNamed => Name is { Length: > 0 };
                }
            }

            #nullable restore
            #endregion

            """
        });
    }

    [Test]
    public void Delegate()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            class Thing { }

            [Mixin]
            class Source
            {
                public delegate Thing ThingAction(Thing aThing);
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                public delegate global::Test.Thing ThingAction(global::Test.Thing aThing);
            }

            #nullable restore
            #endregion

            """
        });
    }

    [Test]
    public void Enum()
    {
        var result = RunMixinGenerator(
            """
            using Mixer;

            namespace Test;

            [Mixin]
            class Source
            {
                protected internal enum Stooges { Larry, Curly, Moe }
            }
            """,
            """
            using Mixer;

            namespace Test;

            [Include<Source>]
            partial class Target { }
            """
        );

        result.ShouldBeGeneratedSources(new()
        {
            ["Test.Target.1.g.cs"] =
            """
            // <auto-generated>
            //   This code file was generated by the 'Mixer' NuGet package.
            //   See https://github.com/sharpjs/Mixer for more information.
            // </auto-generated>

            namespace Test;

            #region Source
            #nullable enable

            partial class Target
            {
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Mixer.Generator", "0.0.0.0")]
                protected internal enum Stooges { Larry, Curly, Moe }
            }

            #nullable restore
            #endregion

            """
        });
    }
}
